- src/Application.ts
- src/ClusterHelper.ts
- src/instance/discord/ChatManager.ts
- src/instance/discord/CommandManager.ts
- src/instance/discord/commands/RestartCommand.ts
- src/instance/globalChat/GlobalChatInstance.ts
- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/MinecraftInstance.ts
- src/instance/minecraft/chat/BlockChat.ts
- src/instance/minecraft/chat/DemoteChat.ts
- src/instance/minecraft/chat/JoinChat.ts
- src/instance/minecraft/chat/KickChat.ts
- src/instance/minecraft/chat/LeaveChat.ts
- src/instance/minecraft/chat/MuteChat.ts
- src/instance/minecraft/chat/OfficerChat.ts
- src/instance/minecraft/chat/OfflineChat.ts
- src/instance/minecraft/chat/OnlineChat.ts
- src/instance/minecraft/chat/PromoteChat.ts
- src/instance/minecraft/chat/PublicChat.ts
- src/instance/minecraft/chat/RepeatChat.ts
- src/instance/minecraft/chat/UnmuteChat.ts
- src/instance/minecraft/handlers/RawChatHandler.ts
- src/instance/minecraft/handlers/SelfBroadcastHandler.ts
- src/instance/minecraft/handlers/StateHandler.ts
- src/instance/webhook/WebhookInstance.ts
Casting the object to the event will remove all warnings to missing fields, which could introduce bugs.
> Backend: Remove all generic cast in event

- src/plugins/WelcomePlugin.ts
each node could have the same plugin enabled. An event sent to all nodes will result in the event being processed multiple times
> bugfix: Welcome message sent multiple times if application running in cluster mode

- src/instance/discord/commands/ListCommand.ts
- src/util/DiscordPager.ts
This should hopefully fix issue #28 
The fix divides the message into multiple smaller one with max size of 3900 character.
Pagination is added to avoid spamming the chat with all the small embeds.
> Add Pagination to Discord command /list

- src/instance/minecraft/MinecraftInstance.ts
Discord have less strict language control by default and isn't as moderated as Minecraft servers. 
Minecraft instance doesn't need to broadcast blocked messages to begin with. 
They are only needed for discord instance to warn users about their language. 
If a message will be blocked by a minecraft instance, then another minecraft instance can not possibly send that message to begin with. Hence, blocking it completely is an optimal fix.
> fix #31 Blocked message event repeats itself nonstop

- src/instance/minecraft/chat/BlockChat.ts
To prevent from having the bot saying slurs and to protect privacy (as a workaround for #36).
> Blur blocked message text and fixes #36

- src/instance/minecraft/MinecraftInstance.ts
Only minecraft chat can create this event, looping the event back to them will create an endless loop.
> Prevent repeat block message from being resend to minecraft instances

- package.json
- src/Application.ts
- src/instance/discord/commands/ListCommand.ts
- src/instance/minecraft/commands/CataCommand.ts
- src/instance/minecraft/commands/GuildCommand.ts
- src/instance/minecraft/commands/LevelCommand.ts
- src/instance/minecraft/commands/NetworthCommand.ts
- src/util/Mojang.ts
The old mojang library is coded in javascript and doesn't have any documentation that can be used for typescript and linters.
> Drop 8 years old mojang library and create basic api that supports typescript

- tsconfig.json
Peer libraries have been giving compile errors preventing. 
Affected libraries are from primarine- projects.
> Suppress libraries errors.

- index.ts
Used to be useful when dynamic loading was used. Now, everything's preloaded and compiled.
> Remove old test loading packages.

- src/instance/minecraft/chat/JoinChat.ts
- src/instance/minecraft/chat/KickChat.ts
- src/instance/minecraft/chat/LeaveChat.ts
In-game event messages for join, leave and kick now contain IGN as a prefix. e.g "@[GUILDNAME] Hxqz joined the guild!"
> Add IGN Prefix

- src/instance/minecraft/MinecraftInstance.ts
When an instance is restarted, it will send a message in guild chat to notify members. e.g "Guild > BRIDGEBOT: @Instance restarting..."
> Added Restarting Message

- src/util/DiscordMessageUtil.ts
This is to fix an issue with non ascii characters. The validation process checks the first 16 letters and if they are invalid, the discord id will be used instead.
This update aims to fix that by first removing all non ascii characters then checking for a proper username after.
> remove all non ascii characters when reading for a discord username

- src/instance/minecraft/commands/CalculateCommand.ts
: is now equal to /
x is now equal to *
Commas will now be parsed out of numbers before trying to evaluate expressions
Shortened command output to not include whole calculation anymore
> Added Support For Different Operators

- src/instance/minecraft/handlers/StateHandler.ts
Stop Minecraft from trying to reconnect if the account has been banned from the server.
> Stop Minecraft From reconnecting after being banned

- src/instance/discord/ChatManager.ts
This is to prevent large messages being instantly sent over multiple messages ingame which can cause the bot to be banned.
> Added truncation to messages over 250 chars

- src/instance/discord/ChatManager.ts
minecraft has a limit of 256 chars per message
256 - 232 = 24
we reserve these 24 spare chars for username, prefix and ...
> Reduced char limit to 232

- src/common/ClientInstance.ts
instead of numbers when displayed.
Example of old display message
> Enhance: Client status now is full words

- config_example.yaml
- index.ts
- package-lock.json
- package.json
- src/Application.ts
- src/instance/socket/ClientSocket.ts
- src/instance/socket/ServerSocket.ts
`Socket.io` is a bloated library that supports too many features the project doesn't need. 
This is why we are falling back to the simple `ws` library. This closes #132
> Simplify Sockets

- config_example.yaml
- src/plugins/auto-restart-plugin.ts
Useful to schedule restarts for the application.
Application left without restarting will consume more RAM till it reaches around 10x its original size.
> feat(plugin): Create auto-restart-plugin

- src/instance/metrics/metrics-instance.ts
url.parse() was deprecated. It was replaced with a simple string split. 
request.url returned the entire path after the hostname like "/path?query=value".
> chore(metrics): Replace a deprecated node method

- src/instance/discord/common/chat-triggers.ts
Discovered by `nicedoggo` on Discord.
> fix(discord): /invite doesn't detect full guild

- src/instance/commands/triggers/runs-to-class-average.ts
People are used to always have the first argument be the username. They are getting confused. Will close #193
> fix(commands): switch !rtca args

- .eslintrc.json
- src/common/plugins.ts
This is useful for future contributors to know what not to import. This will ensure the code base stays clean and not become a spaghetti mess.
> chores(lint): enforce import/no-restricted-paths

- src/instance/discord/discord-instance.ts
Discord officer chat used to be mostly empty and out of touch unlike public chat. This update forwards a copy of events from public to officer making the officer chat a moderator log.
Public only: block due to wording in sent message, bot muted, offline/online player, quest completion, cannot repeat
Officer only: mute/unmute player
both: request to join, join/leave, kick, promote/demote
automated scripting from plugins is left to each script own discretion.
This close #189
> feat(discord): forward more events to discord officer chat

- src/instance/minecraft/handlers/error-handler.ts
This fix #179 by notifying the user and letting the user decide how to handle it. Setting the instance status to FAILED stops it from reconnecting nonstop.
> fix(minecraft): notify when fetched profile is empty

- package-lock.json
- package.json
- src/application.ts
- src/types/bad-words.d.ts
the new major version of bad-words is too buggy to be even released.
Some of the bugs found:
- removes any underscore if it comes directly after \w
- new line character will result in all words seperated by a space to start and end with an underscore like _\w+_
- isProfane() function isn't accurate at all and has different results from the rest of the functions including clean()
> fix(deps): revert and ensure bad-words doesn't update

- src/instance/commands/commands-instance.ts
- src/instance/commands/common/util.ts
- src/instance/commands/triggers/bits.ts
- src/instance/commands/triggers/calculate.ts
- src/instance/commands/triggers/catacomb.ts
- src/instance/commands/triggers/guild.ts
- src/instance/commands/triggers/kuudra.ts
- src/instance/commands/triggers/level.ts
- src/instance/commands/triggers/networth.ts
- src/instance/commands/triggers/runs-to-class-average.ts
- src/instance/commands/triggers/runs.ts
- src/instance/commands/triggers/secrets.ts
- src/instance/commands/triggers/skills.ts
- src/instance/commands/triggers/slayer.ts
- src/instance/commands/triggers/soopy.ts
- src/types/hypixel-api-reborn.d.ts
Many parts of the bridge just throw an error instead of handling exception. These errors usually go all the way up to the last error handler that controls whether the application exits with code 1. 
This patch aims to handle these exceptions and reserving the final error handler for fatal errors only.
> fix(commands): Commands crashes

- src/instance/discord/discord-instance.ts
due to b3214a9a1b1a250c0a639c51785300ccf9862a22
> fix(discord): commands send "event.instanceName" instead of the instance name

- README.md
- package-lock.json
- package.json
- src/instance/commands/commands-instance.ts
- src/instance/commands/triggers/party.ts
| Command                               | When                         | Response                                                                       |
---------------------------------------|------------------------------|--------------------------------------------------------------------------------|
`!parties`                            | there are parties            | `aidn5, parties: 1. aidn5 5 players doing dungeons m7 with 12 hours left\n`    
`!parties`                            | there are no parties         | `aidn5, There are no active parties. You can !startparty`                      
`!endparty`                           | has party                    | `aidn5, party ended.`                                                          
`!endparty`                           | …
> feat(commands): add !parties

- src/instance/minecraft/handlers/state-handler.ts
Upon appealing a security blocked account, a 14 day timer is placed on the account until it unlocks. This scenario creates a unique 'ban screen' message, which should cause the instance to quit and not rejoin until reconnected manually. However, since the message was never scanned for, the default action was to automatically rejoin indefinitely.
> Added handler for new security block message
