aidn3/hypixel-guild-discord-bridge

- src/instance/discord/ChatManager.ts
One of the remnant Javascript code before being converted into Typescript in 35279dc38fdfa50f965acda14cb5ad203c31d314
> backend: convert private function from javascript to typescript

- src/common/ApplicationEvent.ts
- src/instance/discord/DiscordInstance.ts
- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/MinecraftInstance.ts
- src/instance/minecraft/chat/BlockChat.ts
- src/instance/minecraft/chat/DemoteChat.ts
- src/instance/minecraft/chat/JoinChat.ts
- src/instance/minecraft/chat/KickChat.ts
- src/instance/minecraft/chat/LeaveChat.ts
- src/instance/minecraft/chat/MuteChat.ts
- src/instance/minecraft/chat/OfflineChat.ts
- src/instance/minecraft/chat/OnlineChat.ts
- src/instance/minecraft/chat/PromoteChat.ts
- src/instance/minecraft/chat/RepeatChat.ts
- src/instance/minecraft/chat/RequestChat.ts
- src/instance/minecraft/chat/UnmuteChat.ts
- src/plugins/WelcomePlugin.ts
To enforce type and avoid misspellings
> Convert ClientEvent.name from string to enum

- src/instance/minecraft/chat/RepeatChat.ts
- src/instance/minecraft/commands/CalculateCommand.ts
- src/instance/minecraft/commands/CataCommand.ts
- src/instance/minecraft/commands/EightBallCommand.ts
- src/instance/minecraft/commands/ExplainCommand.ts
- src/instance/minecraft/commands/GuildCommand.ts
Altered some strings to be more grammatically accurate and make more sense.
> Grammar fixes

- README.md
- src/instance/minecraft/commands/RouletteCommand.ts
Russian Roulette mini-game command, users can chose a number 1-6 and test their luck for a 15 minute mute or not.
> Add Roulette Command

- src/Application.ts
- src/ApplicationConfig.ts
- src/common/PluginInterface.ts
- src/common/Plugins.ts
- src/plugins/ExamplePlugin.ts
- src/plugins/LimboPlugin.ts
- src/plugins/RegexOptimizePlugin.ts
- src/plugins/WelcomePlugin.ts
onRun function now has one argument called context which contains all current + any future variable.
> Update Plugin API to be more future-proof.

- package-lock.json
- src/instance/discord/commands/ListCommand.ts
- src/instance/minecraft/commands/CataCommand.ts
- src/instance/minecraft/commands/LevelCommand.ts
- src/instance/minecraft/commands/NetworthCommand.ts
- src/type/HypixelApiType.d.ts
- src/type/skyhelper-networth.d.ts
- src/util/SkyblockApi.ts
- tsconfig.json
Add declaration types to old package and internet responses
> Hypixel api type

- src/instance/minecraft/ChatManager.ts
- src/instance/minecraft/chat/BlockChat.ts
- src/instance/minecraft/chat/DemoteChat.ts
- src/instance/minecraft/chat/JoinChat.ts
- src/instance/minecraft/chat/KickChat.ts
- src/instance/minecraft/chat/LeaveChat.ts
- src/instance/minecraft/chat/MuteChat.ts
- src/instance/minecraft/chat/OfficerChat.ts
- src/instance/minecraft/chat/OfflineChat.ts
- src/instance/minecraft/chat/OnlineChat.ts
- src/instance/minecraft/chat/PrivateChat.ts
- src/instance/minecraft/chat/PromoteChat.ts
- src/instance/minecraft/chat/PublicChat.ts
- src/instance/minecraft/chat/RepeatChat.ts
- src/instance/minecraft/chat/RequestChat.ts
- src/instance/minecraft/chat/UnmuteChat.ts
- src/instance/minecraft/common/ChatInterface.ts
Helps with linter and compiler
> Make Minecraft chat modules directly imported.

- src/instance/minecraft/MinecraftInstance.ts
- src/util/SharedUtil.ts
Adds a randomised 6 char string to the end of each command output to bypass Hypixel anti spam being too agressive.
> Anti Spam String

- src/instance/minecraft/commands/RouletteCommand.ts
Trying to validate numbers and NaN and Math.floor and min max number etc. isn't worth maintaining when players can't even see what is happening behind the scenes.
> bugfix: players can pass non number values and always win.

- .eslintrc.json
- src/Application.ts
- src/common/EventHandler.ts
- src/common/Plugins.ts
- src/instance/discord/ChatManager.ts
- src/instance/discord/CommandManager.ts
- src/instance/discord/DiscordInstance.ts
- src/instance/discord/commands/ListCommand.ts
- src/instance/discord/commands/PingCommand.ts
- src/instance/socket/ClientSocket.ts
- src/plugins/RegexOptimizePlugin.ts
- src/util/DiscordPager.ts
- src/util/RateLimiter.ts
Useful to enforce types instead of having a "bypass" type.
> Enable no any rule

- README.md
Offical discord tags added to prove legitimacy
> Added discord tags

- README.md
- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/commands/RockPaperScissorsCommand.ts
A new mini-game command. Rock, paper scissors.
> Rps command

- src/instance/metrics/MetricsInstance.ts
Endpoint for external status checking
> Added /ping

- README.md
- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/commands/RunsCommand.ts
- src/type/hypixel-api-reborn.d.ts
Runs command to check player dungeon floor completions. e.g !runs m7 hxqz
> Runs command

- README.md
- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/commands/KuudraCommand.ts
- src/type/hypixel-api-reborn.d.ts
Command to check players kuudra completions. e.g !kuudra infernal 15h
> Added Kuudra Command

- README.md
- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/commands/SecretsCommand.ts
- src/instance/minecraft/commands/SkillCommand.ts
Self explanatory, fetches players total secrets. e.g !secrets <IGN>
> Secrets command

- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/commands/BitchesCommand.ts
- src/instance/minecraft/commands/CalculateCommand.ts
- src/instance/minecraft/commands/CataCommand.ts
- src/instance/minecraft/commands/EightBallCommand.ts
- src/instance/minecraft/commands/ExplainCommand.ts
- src/instance/minecraft/commands/GuildCommand.ts
- src/instance/minecraft/commands/IqCommand.ts
- src/instance/minecraft/commands/KuudraCommand.ts
- src/instance/minecraft/commands/LevelCommand.ts
- src/instance/minecraft/commands/NetworthCommand.ts
- src/instance/minecraft/commands/RockPaperScissorsCommand.ts
- src/instance/minecraft/commands/RouletteCommand.ts
- src/instance/minecraft/commands/RunsCommand.ts
- src/instance/minecraft/commands/SecretsCommand.ts
- src/instance/minecraft/commands/SkillCommand.ts
- src/instance/minecraft/commands/WeightCommand.ts
- src/instance/minecraft/common/ChatInterface.ts
Added !help and !command
If no args are provided, returns a list of all commands
If a command is provided, returns a description and example of the given command
> Command help

- src/instance/discord/common/DiscordConfig.ts
- src/instance/minecraft/CommandsManager.ts
Fixed message splitting & added 'cmds' and 'cmd' alias
> Fixed message splitting & added 'cmds' and 'cmd' alias

- src/common/ApplicationEvent.ts
- src/instance/minecraft/ChatManager.ts
- src/instance/minecraft/chat/QuestChat.ts
Tried to add guild quest completion. Not entirely sure if regex is correct, very hard to test since guild quests aren't often completed
> Guild quest event

- src/instance/minecraft/CommandsManager.ts
Guess what? I added a single space, had to lint, create branch, commit, pr, have it approved and restart entire service for it to apply.
> Single space added :)

- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/commands/ExplainCommand.ts
- src/instance/minecraft/commands/SecretsCommand.ts
Help commands now send to discord
> Help command to discord

- src/instance/minecraft/handlers/StateHandler.ts
Fixes 'Instance Connected' being triggered twice when joining hypixel then entering limbo. Also fixes false 'disconnects' with warp plugin
> Fix for double connect

- src/instance/minecraft/commands/SecretsCommand.ts
tins have labels, they usually explain the purpose of the contents. im tired, again. approve it, let me sleep. please. the linter... its coming... its after me.
> Added secret average

- src/instance/minecraft/chat/MuteChat.ts
- src/instance/minecraft/chat/UnmuteChat.ts
Yeah does what it says in the title? its like 3am and this took way too long to test :D
> Improved regex to detect guild mutes & swapped embed title to responsible user

- src/instance/discord/ChatManager.ts
Truncate warning seems to appear everywhere
> Fix truncate message and filter

- src/instance/discord/ChatManager.ts
Discord ChatManager.ts used to do multiple IO requests and process text before even checking whether the message is relevant to bridge. This patch will ensure to check first and reuse everything already checked.
> Backend: Optimize Discord chat detection.

- README.md
- src/instance/minecraft/CommandsManager.ts
- src/instance/minecraft/commands/SlayerCommand.ts
- src/type/hypixel-api-reborn.d.ts
Has overview aswell as specific slayer stats. Probably needs some backend polishing
> Added Slayer Command

- .eslintrc.json
- package-lock.json
- src/instance/discord/commands/ListCommand.ts
This should help with the latest Mojang random API outage.
> bug fix: discord command /list sometimes doesn't resolve if an error returned from Mojang API.

- src/instance/minecraft/commands/RouletteCommand.ts
by increasing the chance of losing with every win and by adding a cap to prevent high win streaks that ruins the fun of losing.
The old system was just a flat chance of `1/6`. Some people even managed to reach 24 winstreak. Manual simulations managed to reach even 90 winstreak
This update will make it harder to reach such high winstreaks by:
- capping the win streak to a certain constant
- Increase the chance of losing after the initial couple wins
> Enhance: Make RussianRoulette game more reliable

- package-lock.json
Just a regular update to all packages to patch vulnerabilities if any exist.
> Dependencies Bump: upgrade all packages and their dependencies

- config/log4js-config.json
- index.ts
- src/Application.ts
- src/util/SharedUtil.ts
This update preserves the logs for a longer duration making it viable to check the logs for any activity and member investigation besides debugging
> Preserve logs

- README.md
- src/ClusterHelper.ts
- src/instance/discord/CommandManager.ts
- src/instance/discord/commands/ConnectivityCommand.ts
> Feature: Add discord command /connectivity

- src/Application.ts
- src/common/ApplicationEvent.ts
- src/instance/commands/triggers/RouletteCommand.ts
- src/instance/discord/ChatManager.ts
- src/instance/discord/commands/MuteCommand.ts
- src/instance/discord/commands/UnmuteCommand.ts
- src/instance/minecraft/chat/MuteChat.ts
- src/instance/minecraft/chat/PublicChat.ts
- src/instance/minecraft/chat/UnmuteChat.ts
- src/instance/socket/ClientSocket.ts
- src/instance/socket/ServerSocket.ts
- src/util/PunishedUsers.ts
> Better punishment

- src/instance/discord/CommandManager.ts
- src/instance/discord/commands/LogCommand.ts
- src/util/DiscordPager.ts
> /Log command

- src/common/application-event.ts
This is to clarify documentation and not have the meaning be implicit and concluded from the type. https://github.com/aidn3/hypixel-guild-discord-bridge/pull/167#discussion_r1568996456
> chore(docs): Clarify what to put in "username" field

- README.md
- src/common/application-event.ts
- src/common/client-instance.ts
- src/instance/metrics/application-metrics.ts
- src/instance/minecraft/chat-manager.ts
- src/instance/minecraft/minecraft-instance.ts
- src/plugins/auto-restart-plugin.ts
- src/plugins/dark-auction-plugin.ts
- src/plugins/example-plugin.ts
- src/plugins/limbo-plugin.ts
- src/plugins/punishment-plugin.ts
- src/plugins/reaction-plugin.ts
- src/plugins/starfall-cult-plugin.ts
Improved the markdown, grammar and english quality of several files. Most importantly, `readme.md` has been improved to make more sense. In turn, this should make understanding the aim and potential of the project easier for non native english speakers.
> Better english

- src/instance/discord/commands/punishments.ts
- src/instance/minecraft/chat/public.ts
- src/plugins/punishment-plugin.ts
- src/util/punished-users.ts
This pull request fixes multiple issues in the punishment system:
- punishment duration loses couple seconds after executing the command from discord side
- punishments list is sometimes cleaned when adding a new punishment entry
> fix(punishments): fix punishments various issues

- src/instance/discord/commands/list.ts
This is discovered after testing with an invalid Hypixel API key.
> fix(discord): /list fails to respond if hypixel request fails

- src/instance/commands/triggers/calculate.ts
As we all know, in 2024, it is important to include people of all backgrounds and all cultures.
After using this bot for numerous hours, I have come to the realization that some people aren't represented correctly: asian parents.
It is indeed noticeable that members are able to use the `!calculate` command to get answers to very easy maths, without getting yelled at.
This pull request introduces a fix to this very important lack of representation.
> Asianification

- src/instance/commands/triggers/soopy.ts
Most Soopy commands depend on username context.
> fix(commands): Soopy command cache shared between users

- src/instance/discord/discord-instance.ts
- src/instance/discord/handlers/status-handler.ts
Original Suggestion: ImCosmoXD
> feat(discord): add discord status and activity

- src/instance/discord/commands/list.ts
> feat(discord): preserves /list original sorting order

- package-lock.json
- package.json
- patches/prismarine-auth+2.4.2.patch
This is a live patch to fix an upstream dependency problem that affects all versions.
> fix(depends): Fix upstream dependency prismarine-auth

- src/instance/commands/triggers/catacomb.ts
Just a simple change to add an alias, it's pretty annoying for users
> Add catacombs alias for command

- .github/workflows/publish.yml
- Dockerfile
> feat(workflow): add publish docker/release workflow

- README.md
- index.ts
- src/application.ts
- src/util/shared-util.ts
> docs(app): Document how to use Docker

- .eslintrc.json
- src/application-config-ti.ts
- src/application-config.ts
- src/common/application-event.ts
- src/common/client-instance.ts
- src/configuration-parser.ts
- src/instance/commands/triggers/8ball.ts
- src/instance/commands/triggers/rock-paper-scissors.ts
- src/instance/commands/triggers/runs-to-class-average.ts
- src/instance/commands/triggers/skills.ts
- src/instance/discord/command-manager.ts
- src/instance/discord/commands/about.ts
- src/instance/discord/commands/accept.ts
- src/instance/discord/commands/connectivity.ts
- src/instance/discord/commands/demote.ts
- src/instance/discord/commands/invite.ts
- src/instance/discord/commands/list.ts
- src/instance/discord/commands/log.ts
- src/instance/discord/commands/override.ts
- src/instance/discord/commands/ping.ts
- src/instance/discord/commands/promote.ts
- src/instance/discord/commands/punishments.ts
- src/instance/discord/commands/reconnect.ts
- src/instance/discord/commands/restart.ts
- src/instance/discord/commands/setrank.ts
- src/instance/discord/common/command-interface.ts
- src/instance/discord/discord-pager.ts
- src/instance/minecraft/chat/repeat.ts
- src/instance/minecraft/common/proxy-handler.ts
The default linter uses a regex that allows all uppercase such as "MESSAGES".
The custom regex enforces a true PascalCase converting it to "Messages"
> chore(lint): lint with a better PascalCase

- src/application-config-ti.ts
- src/application-config.ts
config got corrupted due to efcaf9133903a821d39dfd480953ac548bb3a37c
> fix(app): hotfix proxy config

- src/instance/discord/discord-instance.ts
> chore(discord): temp disable profanity warnings notifications on officer chat

- src/instance/commands/triggers/networth.ts
Museum data is no longer required to return a networth calculation 
Also corrected spelling on line 59 of "networth"
> Made museumData optional

- src/instance/commands/commands-instance.ts
- src/instance/commands/triggers/personal-best.ts
- src/instance/commands/triggers/runs.ts
- src/instance/commands/triggers/secrets.ts
- src/types/hypixel-api-reborn.d.ts
Example query: `!pb aidn5 m5`
Example response: `aidn5 finished master mode 5 with an S 3m8s and an S+ 2m52s`
> feat(commands): add !personalbest command

- src/instance/commands/triggers/list.ts
- src/instance/commands/triggers/mute.ts
- src/instance/discord/commands/list.ts
- src/instance/prometheus/guild-online-metrics.ts
- src/instance/users/features/autocomplete.ts
- src/instance/users/features/guild-manager.ts
- src/instance/users/features/scores-manager.ts
- src/utility/timeout.ts
since most information are already displayed from the single command execution.
> refactor(users): unify guild listing result into a single object

- docs/COMMANDS.md
- src/instance/discord/commands/list.ts
> Improved list command
